steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: call-server-service
    entrypoint: "gcloud"
    args:
      - "builds"
      - "submit"
      - "--config"
      - "./server/cloudbuild.yaml"
      - "--substitutions"
      - "_PATH=server"
