spring:
  profiles:
    - mysql
  data:
    rest:
      base-path: /api
  application:
    name: expenses-dashboard-api
  datasource:
    ddl-auto: update
    #password: Development example mypassword
    driver-class-name: com.mysql.cj.jdbc.Driver
    show-sql: true
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
    #ddl-auto: create-drop #  Uncomment for development: recreates the db, not recommended for prod
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
          lob:
            non_contextual_creation: true
  h2:
    console:
    enabled: true
